#!/bin/bash
# matrix-render — Regenerate a plan's traceability-matrix.md from its manifest.tasks[].
#
# traceability-matrix.md is a manifest-derived read-replica: manifest.tasks[] is
# the sole task-framing SoT; this capability renders the canonical one-row-per-task
# matrix (| Task | Build-item | SoT clause (file:§) | Acceptance (checkable) |
# Build artifact | Independent verdict |) inside the
# <!-- matrix:start -->/<!-- matrix:end --> sentinel block and preserves operator
# narrative outside the markers. The render OWNS the four SoT-derived columns
# (Task/Build-item/SoT-clause/Acceptance); the two downstream-filled columns
# (Build artifact / Independent verdict) are human-owned and are PRESERVED across
# re-renders via the prior-notes survivorship pattern (mirrors tasks-render's
# parse_ledger_notes). Closes the manifest <-> traceability-matrix.md drift class
# structurally — the matrix was the 8th incident drift site, and nothing rendered
# or consumed it before this capability.
#
# matrix-render is registered in skills/librarian/capability-registry.json; the
# foundation-manifest is regenerated by construction, never hand-edited.
#
# This render NEVER mutates the manifest and NEVER edits traceability-matrix.md
# outside the sentinels. It is the sibling of tasks-render.sh (read that as the
# exemplar) and is born with the line-anchored sentinel location (a marker counts
# ONLY as a full line consisting of exactly the literal marker) — never the
# first-occurrence substring find() that corrupts a sentinel-in-comment file.
#
# Output Contract
#   Files written: <plan-dir>/traceability-matrix.md (sentinel-bounded region
#     regenerated; operator narrative outside the markers + downstream-filled
#     Build-artifact/Independent-verdict cells preserved); findings to stdout
#     (NDJSON via hooks/lib/findings.sh shape) or $FINDINGS_OUTPUT.
#   Schema gate: the plan manifest validates against
#     schemas/plan-manifest-schema.json BEFORE render (jsonschema when
#     available; structural fallback otherwise — block-and-log on failure).
#   Pre-write validation: resolve <plan-dir>; assert manifest.json present +
#     required fields; refuse to write if the assembled content lacks the
#     sentinel pair (block-and-log; tempfile deleted). Ambiguous marker text
#     (present but not exactly one real start + one real end line, in order) is
#     block-and-log, never write-and-hope.
#   Failure mode: block-and-log; never write-and-hope. Manifest read-only.
#     Atomic temp+rename. Idempotent.
#   plan-manifest-schema degrade-contract: REFUSE-AND-FREEZE (loud-skip) — a schema-invalid manifest is refused (no partial write); the skip is surfaced on stderr ("skipped <plan> — manifest invalid: … fails schema"); the read-replica is never silently frozen.
#
# Finding categories (2):
#   matrix-md-drift       (warning, --check only) on-disk traceability-matrix.md != would-be render
#   matrix-md-regenerated (info-event) traceability-matrix.md regenerated (write) or evaluated (--check)
#
# CLI:
#   matrix-render.sh <plan-dir>            # regenerate <plan-dir>/traceability-matrix.md
#   matrix-render.sh --check <plan-dir>    # parity report + findings; no write
#   matrix-render.sh --help
# <plan-dir> may be absolute or relative to PLANS_ROOT.
#
# Env overrides:
#   PLANS_ROOT / PLANS_DIR   plan-tree root (test isolation)
#   MATRIX_FILE              output file (default: <plan-dir>/traceability-matrix.md)
#   PLAN_MANIFEST_SCHEMA     plan-manifest-schema.json (default: foundation -> live)
#   FINDINGS_OUTPUT          NDJSON sink (default: stdout)
#
# Bash 3.2 clean per R-23. Argv-based Python heredoc per R-24.

set -euo pipefail

CLAUDE_HOME_RES="${CLAUDE_HOME:-$HOME/.claude}"
_REPO_LIB="$(cd "$(dirname "$0")/../../.." 2>/dev/null && pwd)/hooks/lib"
if [[ -z "${PLANS_DIR:-}" ]]; then
  # shellcheck source=/dev/null
  { [ -r "$CLAUDE_HOME_RES/hooks/lib/paths.sh" ] && source "$CLAUDE_HOME_RES/hooks/lib/paths.sh"; } \
    || { [ -r "$_REPO_LIB/paths.sh" ] && source "$_REPO_LIB/paths.sh"; } || true
fi
# Source the canonical finding contract (shape parity; the python heredoc emits
# the same {"finding":...} NDJSON line shape emit_finding produces).
# shellcheck source=/dev/null
{ [ -r "$CLAUDE_HOME_RES/hooks/lib/findings.sh" ] && source "$CLAUDE_HOME_RES/hooks/lib/findings.sh"; } \
  || { [ -r "$_REPO_LIB/findings.sh" ] && source "$_REPO_LIB/findings.sh"; } || true

CHECK_ONLY="false"
TARGET=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY="true"; shift ;;
    -h|--help) awk 'NR==1{next} /^#/{sub(/^# ?/,"");print;next} {exit}' "$0"; exit 0 ;;
    --*) echo "matrix-render: unknown flag '$1'" >&2; exit 2 ;;
    *) TARGET="$1"; shift ;;
  esac
done

if [[ -z "$TARGET" ]]; then
  echo "matrix-render: missing <plan-dir> argument (see --help)" >&2
  exit 2
fi

PLANS_ROOT="${PLANS_ROOT:-${PLANS_DIR:-$HOME/.claude-plans}}"
case "$PLANS_ROOT" in
  */) PLANS_ROOT="${PLANS_ROOT%/}" ;;
esac

case "$TARGET" in
  /*) PLAN_DIR="$TARGET" ;;
  *)  PLAN_DIR="$PLANS_ROOT/$TARGET" ;;
esac
case "$PLAN_DIR" in
  */) PLAN_DIR="${PLAN_DIR%/}" ;;
esac
if [[ ! -d "$PLAN_DIR" ]]; then
  echo "matrix-render: plan dir does not exist: $PLAN_DIR" >&2
  exit 1
fi

MANIFEST_PATH="$PLAN_DIR/manifest.json"
if [[ ! -f "$MANIFEST_PATH" ]]; then
  echo "matrix-render: no manifest.json in $PLAN_DIR" >&2
  exit 1
fi

MATRIX_FILE="${MATRIX_FILE:-$PLAN_DIR/traceability-matrix.md}"

SCHEMA_PATH="${PLAN_MANIFEST_SCHEMA:-}"
if [[ -z "$SCHEMA_PATH" ]]; then
  for candidate in \
    "$CLAUDE_HOME_RES/schemas/plan-manifest-schema.json"; do
    if [[ -f "$candidate" ]]; then SCHEMA_PATH="$candidate"; break; fi
  done
fi

python3 - "$PLAN_DIR" "$CHECK_ONLY" "$SCHEMA_PATH" "$MATRIX_FILE" "$MANIFEST_PATH" <<'PY'
import json
import os
import re
import sys
import tempfile
from datetime import date

plan_dir = sys.argv[1]
check_only = sys.argv[2] == "true"
schema_path = sys.argv[3]
matrix_file = sys.argv[4]
manifest_path = sys.argv[5]

today = date.today().isoformat()
plan_slug = os.path.basename(plan_dir.rstrip("/"))

MATRIX_START = "<!-- matrix:start -->"
MATRIX_END = "<!-- matrix:end -->"
MATRIX_HEADING = "## Traceability matrix"
MATRIX_HEADER = ("| Task | Build-item | SoT clause (file:§) | Acceptance (checkable) "
                 "| Build artifact | Independent verdict |")
MATRIX_DELIM = ("|------|-----------|---------------------|------------------------"
                "|----------------|---------------------|")

with open(manifest_path, encoding="utf-8") as fh:
    manifest = json.load(fh)

if schema_path and os.path.isfile(schema_path):
    try:
        import jsonschema  # type: ignore
        with open(schema_path, encoding="utf-8") as fh:
            _schema = json.load(fh)
        jsonschema.Draft202012Validator(_schema, format_checker=jsonschema.FormatChecker()).validate(manifest)
    except ImportError:
        pass
    except Exception as exc:
        # LOUD-SKIP (direct path; the librarian router surfaces stderr). Ratified form
        # "skipped <plan> — manifest invalid: ...", preserving the "fails schema" substring.
        # Still refuses to render (no partial write); the read-replica is left untouched but
        # the skip is visible instead of an easily-missed stderr line.
        print("matrix-render: skipped %s — manifest invalid: manifest fails schema; "
              "refusing to render: %s" % (plan_slug, exc), file=sys.stderr)
        sys.exit(1)

for req in ("schema_version", "project", "spec_path"):
    if req not in manifest:
        print("matrix-render: manifest missing required field '%s'" % req, file=sys.stderr)
        sys.exit(1)

tasks = manifest.get("tasks") or []
title = manifest.get("title") or manifest.get("project") or plan_slug


def emit(d):
    out = os.environ.get("FINDINGS_OUTPUT", "")
    line = json.dumps(d, separators=(", ", ": "), sort_keys=False)
    if out:
        with open(out, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    else:
        print(line)


# master-detect-and-skip (mirror of tasks-render.sh — same guard, mirror parity). matrix-render is the
# mirror writer of the traceability-matrix.md sentinel region; on a type:master (or
# sub_plans-bearing) manifest tasks[] is empty and parse_prior_rows keys only on T-N ids, so an
# unguarded render rewrites a hand-authored sentinel'd master matrix to a 0-row matrix. Latent
# today (no live master matrix), but armed for the first one. Same drift-sweep.sh master
# predicate as tasks-render + the reconciler (ONE shared detection contract). On a master: emit
# a single level:info finding and exit 0 WITHOUT touching traceability-matrix.md.
if manifest.get("type") == "master" or manifest.get("sub_plans"):
    emit({
        "finding": "master-render-skipped",
        "level": "info",
        "file": os.path.basename(matrix_file),
        "plan_slug": plan_slug,
        "detected_at": today,
    })
    sys.exit(0)


def cell(value):
    s = "" if value is None else str(value)
    s = s.replace("\r", " ").replace("\n", " ")
    s = s.replace("|", "\\|")
    return s.strip()


_TID_RE = re.compile(r"^T-[0-9]+(\.[0-9]+)?$")
_STRUCK_ID_RE = re.compile(r"^~~(.+)~~$")


def _bare_matrix_id(cell_value):
    # DERIVE display-form -> bare id. Mirrors tasks-render's _bare_ledger_id: a struck
    # display id (~~T-1~~) must be de-burred before the _TID_RE match, else the row is
    # skipped and its human-owned survivorship cells are dropped on re-render. matrix-render
    # does not strike ids today, but the parser must be robust to a struck id so this declared
    # mirror stays faithful to parse_ledger_notes (sub-01 class-sweep). _TID_RE stays
    # strict; whole-cell match only.
    m = _STRUCK_ID_RE.match(cell_value.strip())
    return m.group(1).strip() if m else cell_value.strip()


def parse_prior_rows(region):
    """Survivorship: harvest the two human-owned trailing columns (Build artifact,
    Independent verdict) keyed by task id from an existing matrix region. Mirrors
    tasks-render's parse_ledger_notes (:226-238): naive | split, skip the header +
    delimiter rows (their first cell is not a T-N id), take the LAST TWO columns so a
    filled downstream cell survives a re-render. A row must carry >= 6 columns. The id
    cell is de-burred (strike-tolerant) before the match, mirroring parse_ledger_notes."""
    prior = {}
    for line in region.split("\n"):
        if not line.strip().startswith("|"):
            continue
        cols = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cols) < 6:
            continue
        tid = _bare_matrix_id(cols[0])
        if not _TID_RE.match(tid):
            continue
        prior[tid] = (cols[-2], cols[-1])
    return prior


preface, footer = "", ""
prior_rows = {}
sentinel_existed = False
rows_ondisk = 0

if os.path.isfile(matrix_file):
    with open(matrix_file, encoding="utf-8") as fh:
        existing = fh.read()

    # LINE-ANCHORED marker location (born with the T-1 sentinel-in-comment hardening): a
    # marker counts ONLY as a full line consisting of exactly the literal marker (trailing
    # whitespace tolerated). A first-occurrence substring find() would lock onto a marker
    # MENTION inside preface prose/comments and splice the render there; marker text present
    # without exactly one real start + one real end line (in order) is AMBIGUOUS:
    # block-and-log, never write-and-hope.
    def _marker_line_offsets(text, marker):
        offs, pos = [], 0
        for _ln in text.splitlines(True):
            if _ln.rstrip() == marker:
                offs.append(pos)
            pos += len(_ln)
        return offs
    _starts = _marker_line_offsets(existing, MATRIX_START)
    _ends = _marker_line_offsets(existing, MATRIX_END)
    if len(_starts) == 1 and len(_ends) == 1 and _ends[0] > _starts[0]:
        s_idx, e_idx = _starts[0], _ends[0]
        sentinel_existed = True
        preface = existing[:s_idx]
        footer = existing[e_idx + len(MATRIX_END):]
        region = existing[s_idx + len(MATRIX_START):e_idx]
        prior_rows = parse_prior_rows(region)
        rows_ondisk = len(prior_rows)
    elif _starts or _ends or MATRIX_START in existing or MATRIX_END in existing:
        sys.stderr.write(
            "matrix-render: BLOCK — no unambiguous sentinel block in %s "
            "(real start-lines=%d, real end-lines=%d; marker mentions: start=%d, end=%d). "
            "A real marker is a full line consisting of exactly the literal marker; repair "
            "the file (or remove stray marker text) and re-run. No write performed.\n"
            % (matrix_file, len(_starts), len(_ends),
               existing.count(MATRIX_START), existing.count(MATRIX_END)))
        sys.exit(1)
    else:
        # No sentinel yet: split on the canonical heading if present (harvest prior
        # downstream cells from the tail table), else the whole file becomes preface and a
        # fresh sentinel block is appended (non-destructive — never clobbers hand content).
        m = re.search(r"(?m)^## Traceability matrix[ \t]*$", existing)
        if m:
            preface = existing[:m.start()]
            prior_rows = parse_prior_rows(existing[m.start():])
            rows_ondisk = len(prior_rows)
        else:
            preface = existing

if not preface.strip():
    preface = (
        "---\n"
        "title: %s — Traceability Matrix\n"
        "type: traceability-matrix\n"
        "created: %s\n"
        "updated: %s\n"
        "---\n\n"
        "# %s — Traceability Matrix\n\n"
        "Forward + backward traceable. One row per task. The render owns the SoT-derived "
        "columns (Task/Build-item/SoT clause/Acceptance) from manifest.tasks[]; "
        "\"Build artifact\" + \"Independent verdict\" are downstream-filled (verifier) "
        "and preserved across re-renders.\n\n"
    ) % (title, today, today, title)

lines = [MATRIX_HEADING, "", MATRIX_HEADER, MATRIX_DELIM]
for t in tasks:
    tid = t.get("id", "")
    build_item = t.get("build_item", "") or ""
    sot = "; ".join(str(s) for s in (t.get("sot_refs") or []))
    acc = "; ".join(str(a) for a in (t.get("acceptance_criteria") or []))
    prior_ba, prior_verdict = prior_rows.get(tid, ("", ""))
    lines.append("| %s | %s | %s | %s | %s | %s |" % (
        cell(tid),
        cell(build_item),
        cell(sot),
        cell(acc),
        cell(prior_ba),
        cell(prior_verdict),
    ))
lines.append("")

region_inner = "\n".join(lines).rstrip() + "\n"
generated_block = MATRIX_START + "\n\n" + region_inner + "\n" + MATRIX_END

if preface and not preface.endswith("\n"):
    preface += "\n"
if footer and not footer.startswith("\n"):
    footer = "\n" + footer

new_content = preface + generated_block + footer
if not new_content.endswith("\n"):
    new_content += "\n"

existing_content = None
if os.path.isfile(matrix_file):
    with open(matrix_file, encoding="utf-8") as fh:
        existing_content = fh.read()

drift = (existing_content != new_content)

if check_only:
    if drift:
        emit({
            "finding": "matrix-md-drift",
            "file": os.path.basename(matrix_file),
            "plan_slug": plan_slug,
            "rows_ondisk": rows_ondisk,
            "rows_manifest": len(tasks),
            "sentinel_present_bool": sentinel_existed,
            "detected_at": today,
            "first_seen": today,
        })
    emit({
        "finding": "matrix-md-regenerated",
        "file": os.path.basename(matrix_file),
        "plan_slug": plan_slug,
        "tasks_rendered_count": len(tasks),
        "sentinel_recreated_bool": (not sentinel_existed),
        "dry_run": True,
        "drift_detected_bool": drift,
        "detected_at": today,
    })
    print("matrix-render: --check (plan=%s) tasks=%d drift=%s" % (
        plan_slug, len(tasks), str(drift).lower()), file=sys.stderr)
    sys.exit(0)

if MATRIX_START not in new_content or MATRIX_END not in new_content:
    print("matrix-render: refusing to write — sentinel markers missing", file=sys.stderr)
    sys.exit(1)

d = os.path.dirname(matrix_file) or "."
fd, tmp = tempfile.mkstemp(dir=d, prefix=".matrix.", suffix=".tmp")
try:
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    os.replace(tmp, matrix_file)
except Exception:
    if os.path.exists(tmp):
        os.unlink(tmp)
    raise

emit({
    "finding": "matrix-md-regenerated",
    "file": os.path.basename(matrix_file),
    "plan_slug": plan_slug,
    "tasks_rendered_count": len(tasks),
    "sentinel_recreated_bool": (not sentinel_existed),
    "dry_run": False,
    "detected_at": today,
})
PY
