#!/bin/bash
# tasks-render — Regenerate a plan's tasks.md from its manifest.tasks[].
#
# tasks.md is a manifest-derived read-replica: manifest.tasks[] is the
# sole task-state SoT; this capability renders the canonical ledger-at-top +
# per-task-blocks shape (governance/file-type-contracts/tasks.md.json) inside
# the <!-- tasks:start -->/<!-- tasks:end --> sentinel block and preserves
# operator narrative outside the markers. Closes the manifest <-> tasks.md
# drift class structurally.
#
# tasks-render is registered in skills/librarian/capability-registry.json; the
# foundation-manifest is regenerated by construction, never hand-edited.
#
# task-done re-point: tasks-render is the RENDER-side consumer of the canonical
# `<!-- task-done: NN/T-M -->` completion marker (relocated into handoff.md):
# a task whose marker is present in the plan's handoff.md, OR whose manifest
# status is already done/cut (the SoT), renders as ~~strike-through~~ in the
# sentinel-bounded ledger + per-task blocks. The autosync hook
# (hooks/tasks-md-autosync.sh) is the WRITE-side consumer — on the same marker it
# flips manifest.tasks[].status='done' (the SoT) then invokes this body. This
# render NEVER mutates the manifest and NEVER edits tasks.md outside the sentinels.
#
# Output Contract
#   Files written: <plan-dir>/tasks.md (sentinel-bounded region regenerated;
#     operator narrative + per-row Notes preserved); findings to stdout (NDJSON
#     via hooks/lib/findings.sh shape) or $FINDINGS_OUTPUT.
#   Schema gate: the plan manifest validates against
#     schemas/plan-manifest-schema.json BEFORE render (jsonschema when
#     available; structural fallback otherwise — block-and-log on failure).
#   Pre-write validation: resolve <plan-dir>; assert manifest.json present +
#     required fields; refuse to write if the assembled content lacks the
#     sentinel pair (block-and-log; tempfile deleted).
#   Emptiness guard (regression floor): an empty-or-stub manifest.tasks[] over an
#     on-disk sentinel region that carries content this render would not reproduce
#     is REFUSED with the same loud-skip shape the schema gate uses, so a 0-row
#     ledger never lands on top of that region. Predicate + scope at the guard.
#   Failure mode: block-and-log; never write-and-hope. Manifest read-only.
#     Atomic temp+rename. Idempotent.
#   plan-manifest-schema degrade-contract: REFUSE-AND-FREEZE (loud-skip) — a schema-invalid manifest is refused (no partial write); the skip is surfaced on stderr ("skipped <plan> — manifest invalid: … fails schema"); the read-replica is never silently frozen.
#
# Finding categories (2 — §Finding categories):
#   tasks-md-drift       (warning, --check only) on-disk tasks.md != would-be render;
#                        carries a `remedy` field naming the sanctioned repair (re-render
#                        via tasks-render / fix manifest.tasks[]) — never a hand-edit
#   tasks-md-regenerated (info-event) tasks.md regenerated (write) or evaluated (--check);
#                        suppressed under --drift-only (the sweep lane stays silent on
#                        the steady state)
#
# CLI:
#   tasks-render.sh <plan-dir>                 # regenerate <plan-dir>/tasks.md
#   tasks-render.sh --check <plan-dir>         # parity report + findings; no write
#   tasks-render.sh --check --drift-only <dir> # sweep-lane shape: tasks-md-drift only,
#                                              # no info-event/summary; --drift-only
#                                              # without --check is refused (rc=2).
#                                              # Invoked per plan by trinity-drift-detect's
#                                              # replica-freshness delegation, which rides
#                                              # its automatic lanes (librarian-full,
#                                              # session-close step 2d). Compare + emission
#                                              # live HERE only — the delegating sweep
#                                              # carries no second implementation.
#   tasks-render.sh --help
# <plan-dir> may be absolute or relative to PLANS_ROOT.
#
# Env overrides:
#   PLANS_ROOT / PLANS_DIR   plan-tree root (test isolation)
#   TASKS_FILE               output file (default: <plan-dir>/tasks.md)
#   PLANS_RULES_PATH         plans-rules.json (default: foundation -> live)
#   PLAN_MANIFEST_SCHEMA     plan-manifest-schema.json (default: foundation -> live)
#   FINDINGS_OUTPUT          NDJSON sink (default: stdout)
#
# Bash 3.2 clean per R-23. Argv-based Python heredoc per R-24.

set -euo pipefail

CLAUDE_HOME_RES="${CLAUDE_HOME:-$HOME/.claude}"
_REPO_LIB="$(cd "$(dirname "$0")/../../.." 2>/dev/null && pwd)/hooks/lib"
if [[ -z "${PLANS_DIR:-}" ]]; then
  # shellcheck source=/dev/null
  { [ -r "$CLAUDE_HOME_RES/hooks/lib/paths.sh" ] && source "$CLAUDE_HOME_RES/hooks/lib/paths.sh"; } \
    || { [ -r "$_REPO_LIB/paths.sh" ] && source "$_REPO_LIB/paths.sh"; } || true
fi
# Source the canonical finding contract (shape parity; the python heredoc emits
# the same {"finding":...} NDJSON line shape emit_finding produces).
# shellcheck source=/dev/null
{ [ -r "$CLAUDE_HOME_RES/hooks/lib/findings.sh" ] && source "$CLAUDE_HOME_RES/hooks/lib/findings.sh"; } \
  || { [ -r "$_REPO_LIB/findings.sh" ] && source "$_REPO_LIB/findings.sh"; } || true

CHECK_ONLY="false"
DRIFT_ONLY="false"
TARGET=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY="true"; shift ;;
    --drift-only) DRIFT_ONLY="true"; shift ;;
    -h|--help) awk 'NR==1{next} /^#/{sub(/^# ?/,"");print;next} {exit}' "$0"; exit 0 ;;
    --*) echo "tasks-render: unknown flag '$1'" >&2; exit 2 ;;
    *) TARGET="$1"; shift ;;
  esac
done

if [[ -z "$TARGET" ]]; then
  echo "tasks-render: missing <plan-dir> argument (see --help)" >&2
  exit 2
fi

# --drift-only is a CHECK-MODE modifier (the sweep-lane shape: emit only the
# tasks-md-drift finding, no per-plan info-event, no stderr summary). A writing
# run must never carry it silently — refuse the combination loudly.
if [[ "$DRIFT_ONLY" == "true" && "$CHECK_ONLY" != "true" ]]; then
  echo "tasks-render: --drift-only requires --check (it is a check-mode sweep modifier, never a write mode)" >&2
  exit 2
fi

PLANS_ROOT="${PLANS_ROOT:-${PLANS_DIR:-$HOME/.claude-plans}}"
case "$PLANS_ROOT" in
  */) PLANS_ROOT="${PLANS_ROOT%/}" ;;
esac

case "$TARGET" in
  /*) PLAN_DIR="$TARGET" ;;
  *)  PLAN_DIR="$PLANS_ROOT/$TARGET" ;;
esac
case "$PLAN_DIR" in
  */) PLAN_DIR="${PLAN_DIR%/}" ;;
esac
if [[ ! -d "$PLAN_DIR" ]]; then
  echo "tasks-render: plan dir does not exist: $PLAN_DIR" >&2
  exit 1
fi

MANIFEST_PATH="$PLAN_DIR/manifest.json"
if [[ ! -f "$MANIFEST_PATH" ]]; then
  echo "tasks-render: no manifest.json in $PLAN_DIR" >&2
  exit 1
fi

TASKS_FILE="${TASKS_FILE:-$PLAN_DIR/tasks.md}"

RULES_PATH="${PLANS_RULES_PATH:-}"
if [[ -z "$RULES_PATH" ]]; then
  for candidate in \
    "$CLAUDE_HOME_RES/governance/plans-rules.json"; do
    if [[ -f "$candidate" ]]; then RULES_PATH="$candidate"; break; fi
  done
fi
# master-fallback (R4 / H-6): plans-rules.json is repo-only — a clean
# adopter ships ONLY the two bundles (foundation-master + overlay-master), read as ONE merged
# view via hooks/lib/foundation-overlay-load.sh (the R-52 union-load primitive). When the
# loose pillar is absent, resolve the EFFECTIVE `.plans` slot through that merger so this cap
# reads the canonical register and never reads a spoke directly (--force-override = read
# posture per pre-write-guard:91). NOTE: tasks-render does not yet CONSUME rules_path (it is
# passed to the Python body unused); this keeps the existing resolution adopter-correct +
# merger-routed without changing the tolerant no-exit behaviour.
if [[ -z "$RULES_PATH" || ! -f "$RULES_PATH" ]]; then
  for _loader in \
    "$CLAUDE_HOME_RES/hooks/lib/foundation-overlay-load.sh" \
    "$_REPO_LIB/foundation-overlay-load.sh"; do
    [[ -x "$_loader" ]] || continue
    _rt="$(mktemp 2>/dev/null)" || break
    if bash "$_loader" --query '.plans' --force-override > "$_rt" 2>/dev/null \
         && [[ -s "$_rt" ]] && [[ "$(head -c4 "$_rt" 2>/dev/null)" != null ]]; then
      RULES_PATH="$_rt"; trap 'rm -f "$_rt"' EXIT; break
    fi
    rm -f "$_rt"
  done
fi

SCHEMA_PATH="${PLAN_MANIFEST_SCHEMA:-}"
if [[ -z "$SCHEMA_PATH" ]]; then
  for candidate in \
    "$CLAUDE_HOME_RES/schemas/plan-manifest-schema.json"; do
    if [[ -f "$candidate" ]]; then SCHEMA_PATH="$candidate"; break; fi
  done
fi

python3 - "$PLAN_DIR" "$CHECK_ONLY" "$RULES_PATH" "$SCHEMA_PATH" "$TASKS_FILE" "$MANIFEST_PATH" "$DRIFT_ONLY" <<'PY'
import json
import os
import re
import sys
import tempfile
from datetime import date

plan_dir = sys.argv[1]
check_only = sys.argv[2] == "true"
rules_path = sys.argv[3]
schema_path = sys.argv[4]
tasks_file = sys.argv[5]
manifest_path = sys.argv[6]
drift_only = sys.argv[7] == "true"

today = date.today().isoformat()
plan_slug = os.path.basename(plan_dir.rstrip("/"))

SENTINEL_START = "<!-- tasks:start -->"
SENTINEL_END = "<!-- tasks:end -->"
LEDGER_HEADING = "## Task ledger"

with open(manifest_path, encoding="utf-8") as fh:
    manifest = json.load(fh)

if schema_path and os.path.isfile(schema_path):
    try:
        import jsonschema  # type: ignore
        with open(schema_path, encoding="utf-8") as fh:
            _schema = json.load(fh)
        jsonschema.Draft202012Validator(_schema, format_checker=jsonschema.FormatChecker()).validate(manifest)
    except ImportError:
        pass
    except Exception as exc:
        # LOUD-SKIP (direct path; the librarian router surfaces stderr). Ratified form
        # "skipped <plan> — manifest invalid: ...", preserving the "fails schema" substring
        # (internal/tests/ac-plan-manifest-tasks-additionalprops.sh pins it). Still refuses to
        # render (no partial write); the read-replica is left untouched but the skip is visible.
        print("tasks-render: skipped %s — manifest invalid: manifest fails schema; "
              "refusing to render: %s" % (plan_slug, exc), file=sys.stderr)
        sys.exit(1)

for req in ("schema_version", "project", "spec_path"):
    if req not in manifest:
        print("tasks-render: manifest missing required field '%s'" % req, file=sys.stderr)
        sys.exit(1)

tasks = manifest.get("tasks") or []
title = manifest.get("title") or manifest.get("project") or plan_slug
spec_path = manifest.get("spec_path") or ""
# DERIVE: manifest status is no longer stamped into the tasks.md preface (the
# artifact is a manifest-derived replica; manifest.json :: status is the SoT).


def emit(d):
    out = os.environ.get("FINDINGS_OUTPUT", "")
    line = json.dumps(d, separators=(", ", ": "), sort_keys=False)
    if out:
        with open(out, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    else:
        print(line)


# master-detect-and-skip. tasks-render is the sole writer of the tasks.md
# sentinel region, but a type:master (or sub_plans-bearing) manifest carries no per-task
# ledger — its tasks[] is empty (or coordinating-only) and parse_ledger_notes keys only on
# T-N ids — so an unguarded render rewrites the hand-authored `| Sub-plan | Slug | Status |`
# rollup the master template plants inside the sentinels to a 0-row header-only ledger. This
# is the ONE chokepoint every caller flows through (the 3 live hooks + direct/model-routed
# invocation), so the guard lives HERE (not at the hook sites). Reuse the drift-sweep.sh
# master predicate (the master<->sub reconciler's contract) so the two renderers + the
# reconciler share ONE detection contract and nothing new drifts. On a master: emit a single
# observable level:info finding and exit 0 WITHOUT touching tasks.md (the rollup is
# hand-reconciled, never renderer-owned).
if manifest.get("type") == "master" or manifest.get("sub_plans"):
    emit({
        "finding": "master-render-skipped",
        "level": "info",
        "file": os.path.basename(tasks_file),
        "plan_slug": plan_slug,
        "detected_at": today,
    })
    sys.exit(0)


def cell(value):
    s = "" if value is None else str(value)
    s = s.replace("\r", " ").replace("\n", " ")
    s = s.replace("|", "\\|")
    return s.strip()


_TID_RE = re.compile(r"^T-[0-9]+(\.[0-9]+)?$")
_STRUCK_ID_RE = re.compile(r"^~~(.+)~~$")
# A whole-cell braced scaffold placeholder ({{one-line}} double-brace or {one-line} single-brace)
# is NOT a real Note — it must render empty, not be carried forward forever. Whole-cell anchored,
# so a legitimate Note that merely contains braces mid-string (e.g. "see {config}") is preserved.
_PLACEHOLDER_NOTE_RE = re.compile(r"^\{\{.*\}\}$|^\{[^{}]*\}$")


def _bare_ledger_id(cell_value):
    # DERIVE display-form -> bare id. A DONE task renders its ledger id STRUCK (~~T-1~~,
    # strike() below); the carried-Note lookup keys by the BARE manifest id, so a struck
    # display id must be de-burred before the _TID_RE match — otherwise ~~T-1~~ fails the
    # match, its row is skipped, and the hand-authored Note is dropped on the next render
    # (silent data loss). This normalizer is LOCAL to the ledger parser: _TID_RE stays strict
    # (it must keep rejecting ~~T-1~~ as a valid manifest id) and the manifest schema is
    # untouched. The match is whole-cell only, so a stray '~~' inside a title/id cannot spoof it.
    m = _STRUCK_ID_RE.match(cell_value.strip())
    return m.group(1).strip() if m else cell_value.strip()


def parse_ledger_notes(region):
    notes = {}
    for line in region.split("\n"):
        if not line.strip().startswith("|"):
            continue
        cols = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cols) < 5:
            continue
        tid = _bare_ledger_id(cols[0])
        if not _TID_RE.match(tid):
            continue
        note = cols[4]
        if _PLACEHOLDER_NOTE_RE.match(note):
            note = ""
        notes[tid] = note
    return notes


# task-done marker re-point. The canonical
# completion signal is the `<!-- task-done: NN/T-M -->` marker relocated into the
# plan's handoff.md (sub-plan form `NN/T-M`; plan-root form `T-M`). The autosync
# hook flips manifest.tasks[].status='done' (the SoT) on that signal; tasks-render
# is the render-side consumer: a task whose marker is present in handoff.md (OR
# whose manifest status is already done/cut — the SoT) renders as strike-through.
# This NEVER edits tasks.md directly and NEVER mutates the manifest here — it only
# READS the marker + the manifest status to decide the strike-through render.
_MARKER_RE = re.compile(r"<!--\s*task-done:\s*(?:[^/\s]+/)?(T-[0-9]+(?:\.[0-9]+)?)\s*-->")


def scan_handoff_done_markers(pdir):
    done = set()
    hpath = os.path.join(pdir, "handoff.md")
    if not os.path.isfile(hpath):
        return done
    try:
        with open(hpath, encoding="utf-8") as fh:
            text = fh.read()
    except Exception:
        return done
    for m in _MARKER_RE.finditer(text):
        done.add(m.group(1))
    return done


def is_done(task, marker_done):
    return (task.get("status", "") in ("done", "cut")) or (task.get("id", "") in marker_done)


def strike(text, struck):
    s = cell(text)
    if struck and s:
        return "~~%s~~" % s
    return s


# An acceptance criterion is PROSE, but a wikilink-shaped token ([[...]]) inside it
# renders as a LIVE link once the replica sits in the vault view — every such AC
# becomes graph noise (inbound edges to targets that are vocabulary, not notes).
# Quote the shape in backticks at the emit site. Code spans are left untouched, so
# an author's own `[[x]]` never double-wraps and re-rendering is byte-stable.
WIKILINK_SHAPE_RE = re.compile(r"\[\[[^\]]+\]\]")
CODE_SPAN_RE = re.compile(r"`[^`]*`")


def quote_wikilink_shapes(text):
    def _q(seg):
        return WIKILINK_SHAPE_RE.sub(lambda m: "`%s`" % m.group(0), seg)
    parts = []
    last = 0
    for m in CODE_SPAN_RE.finditer(text):
        parts.append(_q(text[last:m.start()]))
        parts.append(m.group(0))
        last = m.end()
    parts.append(_q(text[last:]))
    return "".join(parts)


marker_done = scan_handoff_done_markers(plan_dir)

preface, footer = "", ""
prior_notes = {}
sentinel_existed = False
sentinel_region = ""
ledger_rows_ondisk = 0

if os.path.isfile(tasks_file):
    with open(tasks_file, encoding="utf-8") as fh:
        existing = fh.read()
    # LINE-ANCHORED marker location (sentinel-in-comment hardening): a marker counts ONLY
    # as a full line consisting of exactly the literal marker (trailing whitespace
    # tolerated). A first-occurrence substring find() locks onto a marker MENTION inside
    # preface prose/comments (a hand-authored shape-contract comment can legitimately name
    # both markers on one line), splices the render there, and preserves the real block as
    # a stale footer — silent corruption on any automated manifest-write render. Marker
    # text present without exactly one real start + one real end line (in order) is
    # AMBIGUOUS: block-and-log, never write-and-hope.
    def _marker_line_offsets(text, marker):
        offs, pos = [], 0
        for _ln in text.splitlines(True):
            if _ln.rstrip() == marker:
                offs.append(pos)
            pos += len(_ln)
        return offs
    _starts = _marker_line_offsets(existing, SENTINEL_START)
    _ends = _marker_line_offsets(existing, SENTINEL_END)
    if len(_starts) == 1 and len(_ends) == 1 and _ends[0] > _starts[0]:
        s_idx, e_idx = _starts[0], _ends[0]
        sentinel_existed = True
        preface = existing[:s_idx]
        footer = existing[e_idx + len(SENTINEL_END):]
        region = existing[s_idx + len(SENTINEL_START):e_idx]
        sentinel_region = region
        prior_notes = parse_ledger_notes(region)
        ledger_rows_ondisk = len(prior_notes)
    elif _starts or _ends or SENTINEL_START in existing or SENTINEL_END in existing:
        sys.stderr.write(
            "tasks-render: BLOCK — no unambiguous sentinel block in %s "
            "(real start-lines=%d, real end-lines=%d; marker mentions: start=%d, end=%d). "
            "A real marker is a full line consisting of exactly the literal marker; repair "
            "the file (or remove stray marker text) and re-run. No write performed.\n"
            % (tasks_file, len(_starts), len(_ends),
               existing.count(SENTINEL_START), existing.count(SENTINEL_END)))
        sys.exit(1)
    else:
        m = re.search(r"(?m)^## Task ledger[ \t]*$", existing)
        if m:
            preface = existing[:m.start()]
            prior_notes = parse_ledger_notes(existing[m.start():])
            ledger_rows_ondisk = len(prior_notes)
        else:
            preface = existing

def strip_fm_status(text):
    """DERIVE: drop a top-of-file frontmatter `status:` line (manifest is the sole
    status SoT). Touches ONLY the first --- ... --- block — never body text, the
    Status Key section, or ledger content. Idempotent: no status: line -> unchanged
    (split/join round-trips the exact bytes)."""
    fl = text.split("\n")
    if not fl or fl[0].strip() != "---":
        return text
    close = None
    for i in range(1, len(fl)):
        if fl[i].strip() == "---":
            close = i
            break
    if close is None:
        return text
    kept = [ln for i, ln in enumerate(fl)
            if not (1 <= i < close and re.match(r"^status:(\s|$)", ln))]
    return "\n".join(kept)


def _yq(s):
    s = " ".join(str(s).split())
    if ": " in s or s.endswith(":") or (s and s[0] in "#&*[]{}!|>%@`\"'"):
        return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')
    return s


def _cohort_id(suffix):
    ap = os.path.abspath(plan_dir.rstrip("/"))
    marker = os.sep + ".claude-plans" + os.sep
    rel = ap.split(marker, 1)[1] if marker in ap else os.path.basename(ap)
    parts = [re.sub(r"[^a-z0-9]+", "-", p.lower()).strip("-") for p in rel.split(os.sep)]
    return "plans-" + "-".join([p for p in parts if p] + [suffix])


def upsert_fm_cohort(text):
    """The replica preface carries the full frontmatter cohort plans-schema
    requires (type,title,description,created,updated,id,schema_version).
    Healer form: adds ONLY absent keys and re-stamps a non-canonical type: to
    'tasks'. Present values are never rewritten; status:/tags: are never added
    (manifest owns status; tags are an authoring surface). Idempotent."""
    fl = text.split("\n")
    if not fl or fl[0].strip() != "---":
        return text
    close = None
    for i in range(1, len(fl)):
        if fl[i].strip() == "---":
            close = i
            break
    if close is None:
        return text
    keys = {}
    for i in range(1, close):
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", fl[i])
        if m:
            keys[m.group(1)] = (i, m.group(2).strip())
    add = []
    if "type" in keys:
        if keys["type"][1] != "tasks":
            fl[keys["type"][0]] = "type: tasks"
    else:
        add.append("type: tasks")
    fallback_title = "%s — Tasks" % title
    if "title" not in keys:
        add.append("title: %s" % _yq(fallback_title))
    if "description" not in keys:
        dv = keys.get("title", (None, ""))[1].strip('"').strip("'") or fallback_title
        add.append("description: %s" % _yq(dv))
    if "created" not in keys:
        add.append("created: %s" % today)
    if "updated" not in keys:
        add.append("updated: %s" % today)
    if "id" not in keys:
        add.append("id: %s" % _cohort_id("tasks"))
    if "schema_version" not in keys:
        add.append("schema_version: 1")
    if add:
        fl[close:close] = add
    return "\n".join(fl)


if not preface.strip():
    # DERIVE (manifest is the sole status SoT): tasks.md is a manifest-derived
    # read-replica and no longer carries its OWN status: frontmatter. The fresh
    # preface stamp omits status: entirely — nothing writes artifact status
    # anymore; the plan's authoritative status lives on manifest.json :: status.
    preface = (
        "---\n"
        "title: %s — Tasks\n"
        "type: tasks\n"
        "created: %s\n"
        "updated: %s\n"
        "---\n\n"
        "# %s — Tasks\n\n"
        "**Spec:** `%s`\n"
        "**Last Updated:** %s\n\n"
        "## Status Key\n\n"
        "`not-started` | `in-progress` | `done` | `blocked` | `cut`\n\n"
    ) % (title, today, today, title, spec_path, today)
else:
    # DERIVE: an EXISTING preface must not retain a stale status: line — the manifest
    # is the sole status SoT, so re-derivation = removal. Strip it from the preface's
    # first frontmatter block (idempotent; body/Status-Key/ledger content untouched),
    # so a manifest flip cannot leave the tasks.md preface stale.
    preface = strip_fm_status(preface)

# Every render upserts the required frontmatter cohort into the replica preface —
# absent keys only; canonical type re-stamp; no status/tags (healer form).
preface = upsert_fm_cohort(preface)

lines = [
    LEDGER_HEADING,
    "",
    "| ID | Title | Status | Depends on | Notes |",
    "|----|-------|--------|-----------|-------|",
]
for t in tasks:
    tid = t.get("id", "")
    deps = t.get("depends_on") or []
    deps_cell = ", ".join(deps) if deps else "—"
    struck = is_done(t, marker_done)
    lines.append("| %s | %s | %s | %s | %s |" % (
        strike(tid, struck),
        strike(t.get("title", ""), struck),
        cell(t.get("status", "")),
        cell(deps_cell),
        cell(prior_notes.get(tid, "")),
    ))

lines.append("")
lines.append("---")
lines.append("")
lines.append("## Tasks")
lines.append("")

for t in tasks:
    tid = t.get("id", "")
    deps = t.get("depends_on") or []
    deps_str = ", ".join(deps) if deps else "none"
    struck = is_done(t, marker_done)
    lines.append("### %s: %s" % (strike(tid, struck), strike(t.get("title", ""), struck)))
    lines.append("")
    lines.append("**Status:** %s" % t.get("status", ""))
    lines.append("**Dependencies:** %s" % deps_str)
    lines.append("**Description:** %s" % (t.get("description", "") or ""))
    # Render the optional planner framing fields when present; omit the lines
    # cleanly when absent (a task without them looks exactly as before). These carry the
    # traceability content a planner authors into manifest.tasks[] (build_item = the
    # build-item id; sot_refs = the deepest source-of-truth clauses) so a rendered tasks.md
    # loses no framing content the SoT holds.
    build_item = t.get("build_item")
    if build_item:
        lines.append("**Build item:** %s" % build_item)
    sot_refs = t.get("sot_refs") or []
    if sot_refs:
        lines.append("**SoT refs:** %s" % ", ".join(str(s) for s in sot_refs))
    lines.append("")
    lines.append("**File References:**")
    frefs = t.get("file_references") or []
    if frefs:
        for f in frefs:
            lines.append("- `%s`" % f)
    else:
        lines.append("- —")
    lines.append("")
    lines.append("**Acceptance Criteria:**")
    acs = t.get("acceptance_criteria") or []
    if acs:
        for a in acs:
            lines.append("- [ ] %s" % quote_wikilink_shapes(str(a)))
    else:
        lines.append("- [ ] —")
    lines.append("")
    lines.append("---")
    lines.append("")

region_inner = "\n".join(lines).rstrip() + "\n"
generated_block = SENTINEL_START + "\n\n" + region_inner + "\n" + SENTINEL_END

# --- emptiness guard (REGRESSION FLOOR) -------------------------------------------------
# manifest.tasks[] is the sole task-state SoT, so when it is empty-or-stub the ledger this
# renderer generates is a 0-row table. If the on-disk tasks.md already carries a sentinel
# region with content of its own, that 0-row table replaces it. Stated honestly, that is the
# whole residual: a plan that acquires the sentinel pair AND has an empty tasks[] renders a
# 0-row ledger over whatever is inside them. No such plan exists today — the sentinel-bearing
# empty-tasks members of the corpus are all type:master and exit at the master-detect-and-skip
# above with tasks.md byte-identical — so this guard is a REGRESSION FLOOR that catches the
# state if it is ever entered, not a rescue of a state anything is in.
#
# PREDICATE (a) AND (b), derived from what the two render loops above actually read:
#   (a) tasks[] EMPTY-OR-STUB — absent/empty, or every entry carries no non-empty
#       CONTENT field (title, description, acceptance_criteria, file_references,
#       depends_on, build_item, sot_refs). `id` and `status` are identity + state
#       scaffolding, not rendered content: a task carrying only those renders a row and a
#       block with nothing in them. Any ONE populated content field makes it a real task, so
#       the predicate under-fires on a partially-filled manifest rather than over-firing.
#   (b) a real sentinel pair existed on disk AND its region carries lines THIS render does not
#       reproduce (ordered multiset residue of on-disk region minus generated region). The
#       comparison is against the render's OWN output, which makes the guard idempotent by
#       construction: a region this renderer wrote for this manifest has zero residue and
#       never trips, and the EMPTY pair a fresh scaffold ships (skills/new-plan) has zero
#       residue too, so scaffold-time delegation is untouched.
#
# THE PRESERVATION CONTRACT IS NOT WEAKENED. This renderer owns ONLY the region between its
# sentinels; everything outside stays byte-for-byte. A tasks.md with NO sentinel pair keeps
# every existing byte and gets the pair APPENDED (measured on the largest such plan: 16,162 ->
# 16,324 bytes, twelve lines added, zero removed), so the guard deliberately does not fire
# there — refusing an append would convert a preserving behaviour into a blocking one and
# protect nothing. The predicate keys on the sentinel region for exactly that reason.
#
# SCOPE (reachability, so the guard is not mistaken for a corpus-wide control). Both automatic
# lanes render ONLY the plan whose manifest was just written — hooks/post-manifest-binder-refresh.sh
# (PostToolUse Edit|Write on a plan-tree manifest.json) and hooks/tasks-md-autosync.sh (task-done
# marker -> manifest flip -> render). Neither walks the tree and neither reaches an arbitrary
# plan; the third lane is direct/model-routed invocation. So this body is the ONE chokepoint
# every lane flows through and the guard lives HERE, exactly like the master skip above —
# neither hook carries (or needs) a guard of its own.
#
# REJECTED, and not adopted here: restoring a TTY-presence guard on this capability as an
# interim. It protects nobody (an operator at a terminal reaches the identical render), it is
# defeatable with one token, and it re-blocks the on-demand requirement that motivated its
# removal — a band-aid where the structural refusal is the fix.
_CONTENT_FIELDS = ("title", "description", "acceptance_criteria",
                   "file_references", "depends_on", "build_item", "sot_refs")


def _is_stub_task(t):
    if not isinstance(t, dict):
        return True
    for k in _CONTENT_FIELDS:
        v = t.get(k)
        if isinstance(v, (list, tuple, dict)):
            if len(v) > 0:
                return False
        elif v is not None and str(v).strip() != "":
            return False
    return True


def _region_residue(ondisk, generated):
    """Ordered list of the on-disk region's non-blank lines the generated region does not
    reproduce — i.e. exactly what this render would drop. Empty list == nothing to lose."""
    avail = {}
    for ln in generated.split("\n"):
        s = ln.strip()
        if s:
            avail[s] = avail.get(s, 0) + 1
    residue = []
    for ln in ondisk.split("\n"):
        s = ln.strip()
        if not s:
            continue
        if avail.get(s, 0) > 0:
            avail[s] -= 1
        else:
            residue.append(s)
    return residue


if (not tasks) or all(_is_stub_task(_t) for _t in tasks):
    _residue = _region_residue(sentinel_region, region_inner) if sentinel_existed else []
    if _residue:
        # LOUD-SKIP, same shape as the schema gate above ("skipped <plan> — …", stderr, exit 1):
        # refuse and freeze, never write-and-hope. The read-replica is left untouched and the
        # refusal is visible rather than a silent 0-row overwrite.
        print("tasks-render: skipped %s — manifest.tasks[] is empty-or-stub while the on-disk "
              "tasks.md sentinel region carries %d line(s) this render would not reproduce "
              "(first: %s); refusing to render: the generated ledger is a 0-row table and would "
              "replace that region. manifest.tasks[] is the task-state SoT — repair it and re-run."
              % (plan_slug, len(_residue), _residue[0][:120]), file=sys.stderr)
        sys.exit(1)

if preface and not preface.endswith("\n"):
    preface += "\n"
if footer and not footer.startswith("\n"):
    footer = "\n" + footer

new_content = preface + generated_block + footer
if not new_content.endswith("\n"):
    new_content += "\n"

existing_content = None
if os.path.isfile(tasks_file):
    with open(tasks_file, encoding="utf-8") as fh:
        existing_content = fh.read()

drift = (existing_content != new_content)

if check_only:
    if drift:
        emit({
            "finding": "tasks-md-drift",
            "file": os.path.basename(tasks_file),
            "plan_slug": plan_slug,
            "ledger_rows_ondisk": ledger_rows_ondisk,
            "ledger_rows_manifest": len(tasks),
            "sentinel_present_bool": sentinel_existed,
            # The replica heals at its WRITER, never by hand: re-render via
            # tasks-render.sh <plan-dir>, or correct manifest.tasks[] and let the
            # post-manifest refresh hook re-render. Never hand-edit the generated
            # sentinel region of tasks.md.
            "remedy": "re-render via tasks-render.sh <plan-dir> (or fix manifest.tasks[] and let post-manifest-binder-refresh re-render); never hand-edit the generated region",
            "detected_at": today,
            "first_seen": today,
        })
    # --drift-only is the sweep-lane shape: a corpus walk invoking this check per
    # plan must stay SILENT on the steady state (no per-plan info-event, no
    # per-plan stderr line) so an in-parity corpus produces zero output. The
    # ad-hoc single-plan --check keeps the info-event + summary.
    if not drift_only:
        emit({
            "finding": "tasks-md-regenerated",
            "file": os.path.basename(tasks_file),
            "plan_slug": plan_slug,
            "tasks_rendered_count": len(tasks),
            "sentinel_recreated_bool": (not sentinel_existed),
            "dry_run": True,
            "drift_detected_bool": drift,
            "detected_at": today,
        })
        print("tasks-render: --check (plan=%s) tasks=%d drift=%s" % (
            plan_slug, len(tasks), str(drift).lower()), file=sys.stderr)
    sys.exit(0)

if SENTINEL_START not in new_content or SENTINEL_END not in new_content:
    print("tasks-render: refusing to write — sentinel markers missing", file=sys.stderr)
    sys.exit(1)

d = os.path.dirname(tasks_file) or "."
fd, tmp = tempfile.mkstemp(dir=d, prefix=".tasks.", suffix=".tmp")
try:
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    os.replace(tmp, tasks_file)
except Exception:
    if os.path.exists(tmp):
        os.unlink(tmp)
    raise

emit({
    "finding": "tasks-md-regenerated",
    "file": os.path.basename(tasks_file),
    "plan_slug": plan_slug,
    "tasks_rendered_count": len(tasks),
    "sentinel_recreated_bool": (not sentinel_existed),
    "dry_run": False,
    "detected_at": today,
})
PY
