#!/bin/bash
# migration: 0010-class-a-rules-refresh
# min_from: v0.0.0
# applies_at: v1.18.0
#
# Deliver the Class-A rules retirement + shortening to an EXISTING adopter home. The
# $CLAUDE_HOME/rules/ seeds are written by install.sh's seed_rules_entry, which preserves
# on exist — so a content change never reaches a home that is already seeded, and a seed
# that install.sh stops writing is never removed. This migration is the only delivery path
# for both.
#
# Three arms, all complete-or-no-op, touching ONLY $CLAUDE_HOME/rules/:
#   (a) rules/README.md RETIRE. The README is no longer seeded into the always-on rules
#       directory — the harness loads every .md under rules/ at launch, and this one is
#       authoring documentation, not a runtime instruction. Its canonical copy still ships,
#       at $CLAUDE_HOME/templates/claude-home-rules-readme-template.md, and the write-time
#       [RULES FRONTMATTER] advisory in hooks/pre-write-guard.sh points there. Bytes that
#       match a shipped seed are removed; anything else is adopter content and is preserved
#       under rules/README.md.foundation-retired — a name outside the *.md glob the harness
#       loads, so the bytes survive without costing context every session.
#   (b) rules/{00,10,20,30}-*.md REFRESH. A body that matches a shipped seed is replaced
#       with the current one; a body that is already current is left alone; anything else
#       is adopter-edited and is left exactly as it is, with an advisory naming it. An
#       ABSENT entry is a no-op: install.sh's seeder runs earlier in the same --apply and
#       has already written the current body.
#   (c) rules/25-bounded-spoke-for-cross-cutting-work.md RETIRE. Its guidance is delivered
#       in full by the required SessionStart hook hooks/session-start-home-launch-warn.sh,
#       which fires exactly when the launch directory is $HOME — the case the rule exists
#       to catch. Matching bytes are removed; adopter-edited bytes are left in place.
#
# NOTHING IS DESTROYED, so no confirmation gate is needed: every arm either removes bytes
# this project itself wrote (recognised, not assumed) or preserves the file. Recognition is
# by the sha256 table class-a-rules-sha-table.sh, sourced from this migration's own
# directory and GENERATED by tools/generate-class-a-sha-table.sh from the project's git
# history — these paths are deliberately not foundation-manifest files[] members (that is
# what makes them seed-once), so the baseline-manifest sha resolution the other migrations
# use cannot see them. The table carries every body ever seeded, each in both the bytes the
# seeder writes (no trailing newline) and the same bytes with one, because an editor that
# opens and saves a rule file adds the newline back and the adopter has changed nothing.
# An absent or unreadable table, or a home with no sha tool, degrades to a full no-op: the
# migration never guesses.
#
# Idempotent: a second run finds the README absent or already sidecar'd, every entry equal
# to the current body, and the retired rule gone — no writes, rc 0. A fresh install is a
# full no-op (the seeder has already written the current bodies and never wrote a README).
#
# Advisories go to stderr; stdout stays clean for the runner. python3 is NOT required.
# bash-3.2 clean; set -u.
set -u

CLAUDE_HOME_RES="${CLAUDE_HOME:-$HOME/.claude}"
case "$CLAUDE_HOME_RES" in */) CLAUDE_HOME_RES="${CLAUDE_HOME_RES%/}" ;; esac
RULES_DIR="$CLAUDE_HOME_RES/rules"

# --- recognition table (sourced from this migration's own directory) ---------
MIG_SELF_DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd)" || MIG_SELF_DIR=""
TABLE="$MIG_SELF_DIR/class-a-rules-sha-table.sh"
if [ -z "$MIG_SELF_DIR" ] || [ ! -f "$TABLE" ]; then
  printf '0010: recognition table not found beside this migration — cannot tell shipped bytes from adopter bytes; no-op (nothing changed)\n' >&2
  exit 0
fi
# shellcheck disable=SC1090
. "$TABLE" || {
  printf '0010: recognition table unreadable — no-op (nothing changed)\n' >&2
  exit 0
}

# --- sha helper (pure shell; degrades to "" so an unrecognisable file is kept) -
file_sha() {  # $1 = abs path -> sha256 hex, or "" if no sha tool / unreadable
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" 2>/dev/null | awk '{print $1}'
  else
    printf ''
  fi
}
stdin_sha() {  # sha256 hex of stdin, or "" if no sha tool
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 2>/dev/null | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum 2>/dev/null | awk '{print $1}'
  else
    cat >/dev/null; printf ''
  fi
}

# --- oldest/empty precondition: absent rules dir -> no-op --------------------
if [ ! -d "$RULES_DIR" ]; then
  printf '0010: rules dir absent (%s) — no-op (nothing to refresh)\n' "$RULES_DIR" >&2
  exit 0
fi

# --- (a) rules/README.md retire ----------------------------------------------
readme="$RULES_DIR/README.md"
if [ -f "$readme" ]; then
  rsha="$(file_sha "$readme")"
  if [ -n "$rsha" ] && class_a_readme_shas | grep -qxF "$rsha"; then
    if rm -f "$readme" 2>/dev/null; then
      printf '0010: removed rules/README.md (bytes match a shipped seed). The canonical copy is templates/claude-home-rules-readme-template.md under %s/templates/.\n' "$CLAUDE_HOME_RES" >&2
    else
      printf '0010: rm failed for rules/README.md — left in place\n' >&2
    fi
  elif [ -e "$readme.foundation-retired" ]; then
    printf '0010: rules/README.md carries content this project did not write, and rules/README.md.foundation-retired already exists — both left untouched (nothing overwritten). Move or delete one of them by hand if you want the rules dir clean.\n' >&2
  elif mv -f "$readme" "$readme.foundation-retired" 2>/dev/null; then
    printf '0010: rules/README.md carries your own edits — preserved as rules/README.md.foundation-retired. The name is outside the *.md set the harness loads, so the bytes are kept without costing context every session.\n' >&2
  else
    printf '0010: could not preserve rules/README.md as a sidecar — left in place\n' >&2
  fi
fi

# --- (b) rules/{00,10,20,30}-*.md refresh ------------------------------------
for fname in $(class_a_live_entries); do
  [ -n "$fname" ] || continue
  target="$RULES_DIR/$fname"
  [ -f "$target" ] || continue                  # absent -> the seeder already wrote it
  dsha="$(file_sha "$target")"
  [ -n "$dsha" ] || continue                    # no sha tool -> keep, never guess
  cur_sha="$(class_a_current_body "$fname" | stdin_sha)"
  cur_sha_nl="$( { class_a_current_body "$fname"; printf '\n'; } | stdin_sha)"
  if [ "$dsha" = "$cur_sha" ] || [ "$dsha" = "$cur_sha_nl" ]; then
    continue                                    # already current -> no-op
  fi
  if class_a_historical_shas "$fname" | grep -qxF "$dsha"; then
    tmp="$target.tmp.$$"
    if class_a_current_body "$fname" > "$tmp" 2>/dev/null && mv -f "$tmp" "$target" 2>/dev/null; then
      printf '0010: refreshed rules/%s to the current shipped body (the copy on disk matched an older shipped body)\n' "$fname" >&2
    else
      rm -f "$tmp" 2>/dev/null
      printf '0010: could not refresh rules/%s — left in place\n' "$fname" >&2
    fi
  else
    printf '0010: rules/%s carries your own edits — left exactly as it is. The shipped body was shortened; compare it against install.sh if you want the new wording.\n' "$fname" >&2
  fi
done

# --- (c) rules/25-bounded-spoke-for-cross-cutting-work.md retire -------------
retired="$(class_a_retired_entry)"
if [ -n "$retired" ] && [ -f "$RULES_DIR/$retired" ]; then
  qsha="$(file_sha "$RULES_DIR/$retired")"
  if [ -n "$qsha" ] && class_a_historical_shas "$retired" | grep -qxF "$qsha"; then
    if rm -f "$RULES_DIR/$retired" 2>/dev/null; then
      printf '0010: removed rules/%s (bytes match the shipped seed). The same guidance is delivered by the SessionStart hook hooks/session-start-home-launch-warn.sh, exactly when the launch directory is your home directory.\n' "$retired" >&2
    else
      printf '0010: rm failed for rules/%s — left in place\n' "$retired" >&2
    fi
  else
    printf '0010: rules/%s carries your own edits — left exactly as it is. It is no longer shipped; the SessionStart hook hooks/session-start-home-launch-warn.sh carries the same remedy.\n' "$retired" >&2
  fi
fi

exit 0
