#!/bin/bash
# class-a-rules-sha-table.sh — GENERATED by tools/generate-class-a-sha-table.sh.
# NEVER hand-edit. Regenerate (and commit in the same commit) whenever a Class-A
# rule body in install.sh or templates/claude-home-rules-readme-template.md changes.
#
# Sourced by 0010-class-a-rules-refresh.sh. Deliberately NOT named NNNN-*.sh: the
# runner selects migrations by that glob and would otherwise execute this data file.
#
# The recognition sets below are the sha256 of every byte-sequence install.sh has
# ever written to $CLAUDE_HOME/rules/. Each rule body appears twice — as the seeder
# writes it (no trailing newline) and with one — so a file an editor re-saved is
# still recognised as unmodified. A sha that is NOT in these sets means adopter
# bytes, and the migration preserves the file.
#
# bash-3.2 clean. Pure data + selector functions; sources nothing, writes nothing.

# Every shipped rules README template body, and each of those bodies with the
# retired upgrade-lane caveat block appended.
class_a_readme_shas() {
  cat <<'CLASSA_README_SHAS'
3318d25ac3c3cd8b641ecaa1ff772d82fd449d5487c0381bf119acc54a2c54b3
33954e0a7fbd2d7bdd853da17c8b5f28a655964fd00c81e0b1b651765406bb0f
77cec70a0329dfc3f39fec7968ecdedf8c3388610362283eda6f74e3a1207f19
79423fe8a197607f94cb4491d1b92dda539e2bdbcb48437546c0ac7f387e93df
7eddc52216ab66e43de73d437831b2ef1fca20affd6b6171ab269e0ccba2f300
88b7c9052a676903749d1077f1f3dc5f39c9046cfeeed01501f0773396a7a9e6
8f5108e52293897f15fcb30dd8ce07605c65eb447e6c408fb538031d1dfd6913
d6717f8249bd0ce1d8aebada97358f1e6b5d1ad25ce7ed2b7b1cf365f812207c
CLASSA_README_SHAS
}

# Every shipped body of each Class-A rule entry, including the retired
# 25-bounded-spoke-for-cross-cutting-work.md.
class_a_historical_shas() {  # $1 = rule filename
  case "$1" in
    00-project-binder-pointer.md)
      cat <<'CLASSA_ENTRY_SHAS'
1ac166417ec6faee1307683ad5eb2f136b06017c702d7d31336606a07485ada2
4fe8620b5d2ae6099770cd6033c56751e56ea5bfe4ba4985aabd306ba5664ba9
52b930eb12bf97dbba654dc9ad50746167497855f02d80570fac133652111c74
58229a00db8b25f61bb98d2ec7e5573f0a24bf103cfab5a8f1140a4300d6f773
6290bc0025ebd9ad1c2d855715a13567c365f796ad8351f70c4e158caad9d52c
88b970047a1459421e5e2c61fe3a02021e5bae1b2c76209eb426ffa9e62deeb8
8d327cfef88ccbba0e86481d5ac7c77138e3a1f8f9452c3a907749846562d4fe
aa1516d33761768f5daba1bdab94fd522848e6c7634c178cef4404a683ebeb5c
c33c7a8cb773cb0f7aa17992b1cc29387c4fe028215f0bc790a4e532f6d359fc
f6c82ad8360dfe85173ca1ac1fa8fbc3a9960f1a316c652b327981f8519e1cd9
CLASSA_ENTRY_SHAS
      ;;
    10-pre-research-library-check.md)
      cat <<'CLASSA_ENTRY_SHAS'
2d57e6b4008833a4e6e8bad6865d751d1788d97ef3e50ccfcb41bbae75f5e678
30b3465d579d5a80826b6f0707e5b9bdc1135032ae7adf6e71aa869e618b7160
bb80e7e19b49bbe702473d1dbff7c36bc21c18a083b49c91006b6d220618541d
ee937c91234480b1dca01127c59958ef2b55398ea10742bf9de43f1ff42a4e7e
CLASSA_ENTRY_SHAS
      ;;
    20-work-project-register.md)
      cat <<'CLASSA_ENTRY_SHAS'
1e6b86cdb4d8ee7a00a6c58c333bdfbbaf2729ca26846bed81bc78b2059381bd
5bd8c41f4569eccc334bcfa8b5ca69fdd26c2194a28bfb328bbabbf75939c1b5
5edaab7e005d8dce829a0cbfa8e79417fd16819bf0fde1a7072cf631b964ca58
c7e3cacff6b77759374b0571ff79e5b5b42a17a7e3712a6ba288c468c5c78c64
c8f2dcd036c6577197cee61969c2b79c31cb808158d7334848805e930743144f
fae54318a41c502a4e611d321ad3b506d9b2dda2a6014484fc1147ea4a072545
CLASSA_ENTRY_SHAS
      ;;
    30-durable-artifact-routing.md)
      cat <<'CLASSA_ENTRY_SHAS'
14a07aa27a97d25168c6134007e0aba9949c9edfd46445d6c5dbc4a06a02b7ee
2869478b69d43353b04c0956e9f88a1be69694586aa20b3b70d805d09cdbc0c0
7df072390b6f8d6d8496db98e17e94af2c3e4fd1a6d29a0fbdc320eae35ab1bc
ef92540c1a40278825333e8ebe00f520d3863bcef77060c67976b86f2f4d7ef3
CLASSA_ENTRY_SHAS
      ;;
    25-bounded-spoke-for-cross-cutting-work.md)
      cat <<'CLASSA_ENTRY_SHAS'
661774cfdb063d335ae8ff8806aa381274adcf20fc83895d7b95edad80c9de3d
ba73b15655c867f24857f469b2fc32010b20b7d9f85b66c7b2a937cbe5a19463
CLASSA_ENTRY_SHAS
      ;;
  esac
}

# The rule entries install.sh currently seeds, and the retired one it no longer does.
class_a_live_entries() {
  cat <<'CLASSA_LIVE'
00-project-binder-pointer.md
10-pre-research-library-check.md
20-work-project-register.md
30-durable-artifact-routing.md
CLASSA_LIVE
}

class_a_retired_entry() { printf '%s' '25-bounded-spoke-for-cross-cutting-work.md'; }

# The CURRENT body of each live entry, carried in the same heredoc form install.sh
# uses, so the bytes this table replays and the bytes install.sh seeds are identical
# by construction.
read -r -d '' class_a_current_body_00 <<'CLASSA_BODY_00' || true
# Project binder — the situating card is the eager, machine-derived cover

Inside a registered spoke, the situating card (`~/.claude-plans/_projects/<spoke>/_situating.md`) is already in your context — injected at SessionStart from the plans' manifests (plan roster, status, active focus, latest-handoff pointers). Follow its pointers (research-index, decision-log, handoff-chronicle) on demand; never preload every binder index. No card for this spoke yet: run `librarian plan-research-index`.
CLASSA_BODY_00
read -r -d '' class_a_current_body_10 <<'CLASSA_BODY_10' || true
# Before researching — check the library first

Before any research-class task, read `~/.claude-plans/_library/_index.md` and, on a topic match, that topic's `_index.md` + article BEFORE researching fresh (stale coverage: validate / use-as-is / research-fresh). Advisory only. The `pre-research-check` UserPromptSubmit hook injects the same signal when it detects research intent; this rule is the degraded layer for prompts the heuristic misses.
CLASSA_BODY_10
read -r -d '' class_a_current_body_20 <<'CLASSA_BODY_20' || true
# New ~/work project — register before the first write

Starting a project under `~/work/<spoke>/` (exactly one level down): run `/govern register --kind project` from that directory BEFORE any `mkdir`/write. It records the spoke in the anchored-spoke registry, scaffolds the layout (`--layout flat` default; `--layout master --first-sub <name>` for a master with sub-projects), and emits the `Work/<spoke>/**` routing rule so write-time governance fires. Proactive on-ramp, never a gate.
CLASSA_BODY_20
read -r -d '' class_a_current_body_30 <<'CLASSA_BODY_30' || true
# Durable artifact routing — research output lands in its owning context

The plans root (`~/.claude-plans/`) is a CLOSED namespace (`plans-rules.json :: root_namespace`; pre-write-guard denies root writes; `librarian placement-validate` sweeps). Route durable outputs (registers, memos, ledgers, syntheses) by five clauses:

1. Outside any plan's scope: mint the owning plan first — `promote-from-inbox.sh --capture <slug>`, then `promote-from-inbox.sh <slug>` — and land the artifact in that plan's `_research/`.
2. In a work-spoke session: land FLAT in the spoke's `reference/` (single-level `.md`; nesting is index-invisible).
3. About the WORLD → the vault; about the SYSTEM or the work itself → the owning plan's `_research/`.
4. The scratchpad is transit: `mv` into `<plan>/_research/` at graduation; `research_artifacts[]` derives at session close (plan-research-declare) — never a hand-kept second declaration.
5. `_library/` is universal-only; project-specific research stays with its plan.
CLASSA_BODY_30

class_a_current_body() {  # $1 = rule filename
  case "$1" in
    00-project-binder-pointer.md) printf '%s' "$class_a_current_body_00" ;;
    10-pre-research-library-check.md) printf '%s' "$class_a_current_body_10" ;;
    20-work-project-register.md) printf '%s' "$class_a_current_body_20" ;;
    30-durable-artifact-routing.md) printf '%s' "$class_a_current_body_30" ;;
  esac
}
